[package]
name="029_bipmatch"
authors=["David J. Pearce"]

[build]
platforms=["whiley"]

[build.whiley]
source="/"

[check]
min=-1
max=4
length=4
depth=1
ignores=["main"]

[dependencies]
std="0.3.2"

