[package]
name="019_findcuts"
authors=["David J. Pearce"]
version="0.1.0"

[build]
platforms=["whiley","boogie"]

[build.whiley]
source="/"

[build.boogie]
timeout=60
useArrayTheory=false

[dependencies]
std="0.3.2"
